name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin

  validate-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          package-manager-cache: false
      - run: npm run check
